---
_target_: flwr.server.strategy.FedAvg
fraction_fit: 0.01
min_fit_clients: ${num_clients_per_round_fit}
fraction_evaluate: 0.01
min_evaluate_clients: ${num_clients_per_round_eval}
min_available_clients: ${num_clients}
on_fit_config_fn:
  _target_: server.get_on_fit_config
  config: ${config_fit}
