---

num_rounds: 10
num_clients: 10
batch_size: 32
num_clients_per_round_fit: 3
num_clients_per_round_eval: 5

config_fit:
  lr: 0.0003
  momentum: 0.9
  local_epochs: 1


defaults:
  - model: nanoGPT
  - strategy: fedavg
  - optimizers: sgd
